# This is the configuration file for Travis CI, an online continuous integration service.
language: cpp
before_install:
  # Installation of dependencies
  - sudo apt-get update -qq
  - sudo apt-get install cmake libhdf5-openmpi-dev libopenmpi-dev -yq
  # Installation of a newer version of CMake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
  - tar -zxf cmake-3.2.1.tar.gz
  - cd cmake-3.2.1/
  - ./configure
  - make -j
  - sudo make install -j
  - cd ..
  # Installation of newer version of HDF5
  - wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.14.tar.gz
  - tar -zxf hdf5-1.8.14.tar.gz
  - cd hdf5-1.8.14
  - ./configure
  - make -j
  - sudo make install -j
  - cd ..
  # Installation of newer version of OpenMPI
  - wget http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.4.tar.gz
  - tar -zxf openmpi-1.8.4.tar.gz
  - cd openmpi-1.8.4
  - ./configure
  - make -j
  - sudo make install -j
  - cd ..
