# This is the configuration file for Travis CI, an online continuous integration service.
language: cpp

before_install:
  - export NUM_THREADS=1
  # Installation of dependencies
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-openmpi-dev libcppunit-dev -y --quiet
  # Installation of a newer version of CMake
  #- wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
  #- tar -zxf cmake-3.2.1.tar.gz
  #- cd cmake-3.2.1/
  #- ./configure
  #- make -j$NUM_THREADS --silent
  #- sudo make install -j --silent
  #- cd ..
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
  - tar -zxf cmake-3.2.1-Linux-x86_64.tar.gz
  - cmake-3.2.1-Linux-x86_64/bin/cmake --version
  # Installation of newer version of HDF5
  #- wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.14.tar.gz
  #- tar -zxf hdf5-1.8.14.tar.gz
  #- cd hdf5-1.8.14
  #- ./configure
  #- make -j$NUM_THREADS --silent
  #- sudo make install -j --silent
  #- cd ..
  # Installation of newer version of OpenMPI
  - wget http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.4.tar.gz
  - tar -zxf openmpi-1.8.4.tar.gz
  - cd openmpi-1.8.4
  - ./configure
  - make -j$NUM_THREADS --silent
  - sudo make install -j --silent
  - cd ..
  
install:
  - export MPI_ROOT_DIR=/usr/local/lib/openmpi
  - mkdir build
  - cd build
  - ../cmake-3.2.1-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCDMATH_WITH_TESTS=ON -MEDFILE_USE_MPI=ON ..
  - make
  - sudo make install -j --silent
  - cd ..
  
script:
  - cd build
  - make test
  - cd ..
