# This is the configuration file for Travis CI, an online continuous integration service.
language: cpp
before_install:
  - sudo apt-get update -qq
  - yes | sudo apt-get upgrade cmake
  - sudo apt-get install libhdf5-openmpi-dev libopenmpi-dev -y
