# This is the configuration file for Travis CI, an online continuous integration service.
language: cpp
before_install:
  # Installation of a newer version of CMake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
  - tar -zxf cmake-3.2.1.tar.gz
  - cd cmake-3.2.1/
  - ./configure
  - make
  - sudo make install
  - cd ..
  # Installation of dependencies
  - sudo apt-get update -qq
  - sudo apt-get install cmake libhdf5-openmpi-dev libopenmpi-dev -y
